####Matrix配置-config.yml###################################################
#
# 你好，欢迎使用Matrix反作弊，这是config.yml，用来定义矩阵的全局设置。
#
# -如果遇到任何问题，请到我们官方的Discord群寻求帮助：https://discord.gg/pEvY55J
#
# 有用的链接：
# WebStie：https://matrix.rip
# Discord：https://discord.gg/pEvY55J
# Wiki：https://wiki.matrix.rip
# Issue Tracker：https://github.com/jiangdashao/Matrix-Issues/issues
#
# 无论如何，感谢您使用Matrix反作弊！❤
#
# 来自翻译者（李本伟·一世）的补充说明：鄙人对于作弊功能的翻译是在参考大多数的“外挂MOD汉化、外挂客户端汉化、魔改水影等”情况下翻译的；如有不对或更好的翻译请发邮件至：libw@libw.cc，感谢您对我翻译工作（然而大多数是机翻）的支持与信任~
#
###################################################################################

# Matrix是否应该在启动时检查更新？
check_update: true

# 高级用户-验证高级/企业用户的身份
#
# 这是一个为付费用户提供更好服务的认证系统。
# 如果您是高级用户，您将获得更多额外的杀戮光环/自动搭路/等等（KillAura/Scaffold/etc）检查。
# 如果您是免费版用户，则可以忽略此部分。
#
# 除了免费版和付费版，还有企业版。
# 你可以在Discord官方服务器的#premium-version频道查看它们的区别
premium_user:
  # 登录用户名
  user: ''

  # 登录密码
  password: ''

# Matrix是否应该从其它服务器（使用HTTP(s)）加载配置文件（但仅适用于“checks.yml”！）
# 有些大型服务器有几十个甚至上百个子服务器，更新配置文件对它们来说非常麻烦。
# 此功能可以帮助Matrix直接从中心地址加载配置文件。
cloud_config:
  # 启用此功能？（默认：假）
  enable: false

  # 这里可以添加多个链接，可以避免链接下线导致配置文件丢失
  # 如果所有链接都下线，Matrix将使用默认配置
  links:
    - '你的配置文件链接'

# 权限缓存刷新间隔（单位：秒，默认：15）
permission_refresh_interval: 15

# 启用BungeeCord GeyserMC支持？
# Matrix支持两种方式运行GeyserMC：
# 1.Spigot Mode：在Spigot中安装GeyserMC/FloodGate，不需要修改这个设置，Matrix会自动支持
# 2.Bungee Mode：当GeyserMC安装在BungeeCord中时，需要开启该选项，同时在BungeeCord中安装Matrix
# 注意：如果您尚未在BungeeCord中安装GeyserMC，请勿启用此选项
bungee_geysermc_support: false

# 如果有人被使用/matrix kick踢出，是否会有闪电视觉效果
kick_strike_lightning: true

# 服务器滞后保护
# 当你的服务器滞后时自动禁用一些检查。
# 这可以防止大多数（但不是全部）误报的发生。
tps_protection:
  # 启用此功能？
  enable: true

  # 触发保护所需的最低TPS
  min_tps: 17.0

  # 滞后尖峰阈值（毫秒）
  # 如果服务器在一段时间内没有响应，则关闭检查
  lag_threshold: 1000

# 记录违规日志（默认值：true）
# 将所有违规记录到文件中。
# 文件可以在/plugins/Matrix/logs中找到
# 警告：如果您使用的是BungeeCord，我建议将其设置为False。
# 这将防止存储无用的日志文件并占用宝贵的磁盘空间。
log_file: true

# 删除过期日志文件（天）
# 如果日志文件存储超过指定天数，则日志文件将被删除
# 您可以将其设置为 `-1` 以禁用此功能
delete_time: 30

# 拒绝绕过权限（默认值：false）
# 通过将此选项设置为True，您将强制Matrix检查服务器上的每个人，包括具有操作员身份的任何人。
# 通过将此选项设置为True，您可以运行必要的测试，而无需删除您的操作员状态。
disable_bypass_permission: false

## 重新登录时间
# 玩家被踢后多久可以登录（秒）也可以设置-1禁用此功能
relog_time: 5

# 禁用组件
# 您可以在此处禁用特定的子检查，而不是禁用整个检查，您可以在详细消息的末尾找到组件名称示例：如果您在列表中添加“speed.web”，则将禁用SpeedWeb检查
disabled_components:
  - 'example entry'

# 自定义VL权重（格式：component: new vl weight）
custom_vl_weight:
  - 'example_component:5'

# 虚假的反作弊命令
# Matrix是否应该注册一些虚假的反作弊命令？
fake_anticheat:
  aac: false
  spartan: false
